services:
  - type: web
    name: dissertation
    env: python
    region: oregon
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && python src/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /healthz
    autoDeploy: true
    plan: free
    branch: main
    rootDir: server
